// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHJRWwdml-fLTEiU0skMeqhl_AgwFmbI',
    appId: '1:963571412173:web:aeffff24eb25fccdbe0d84',
    messagingSenderId: '963571412173',
    projectId: 'oumas-delicacy',
    authDomain: 'oumas-delicacy.firebaseapp.com',
    storageBucket: 'oumas-delicacy.firebasestorage.app',
    measurementId: 'G-QSF57Q8352',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0wOgkb1hjcJRIIPBeqONerFHK5zcc1g',
    appId: '1:963571412173:ios:82628723a2d4810bbe0d84',
    messagingSenderId: '963571412173',
    projectId: 'oumas-delicacy',
    storageBucket: 'oumas-delicacy.firebasestorage.app',
    iosBundleId: 'com.example.oumasDelicacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEHJRWwdml-fLTEiU0skMeqhl_AgwFmbI',
    appId: '1:963571412173:web:8a76df0f199747aabe0d84',
    messagingSenderId: '963571412173',
    projectId: 'oumas-delicacy',
    authDomain: 'oumas-delicacy.firebaseapp.com',
    storageBucket: 'oumas-delicacy.firebasestorage.app',
    measurementId: 'G-WW1JL6WNQN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0wOgkb1hjcJRIIPBeqONerFHK5zcc1g',
    appId: '1:963571412173:ios:f1e3af9d9ecda724be0d84',
    messagingSenderId: '963571412173',
    projectId: 'oumas-delicacy',
    storageBucket: 'oumas-delicacy.firebasestorage.app',
    iosBundleId: 'com.oumasdelicacy.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Gx85_uacPeG5_9oQkZXQ2JfiPsmycJA',
    appId: '1:963571412173:android:3429b0a72995934bbe0d84',
    messagingSenderId: '963571412173',
    projectId: 'oumas-delicacy',
    storageBucket: 'oumas-delicacy.firebasestorage.app',
  );

}