// lib/main.dart
// ignore_for_file: unused_import

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
// If you ran `flutterfire configure`, this file will exist:
import 'firebase_options.dart' show DefaultFirebaseOptions;

import 'screens/login_screen.dart';
import 'services/auth_service.dart';
import 'providers/cart_provider.dart';
import 'providers/menu_provider.dart';
import 'providers/order_provider.dart';
import 'providers/rider_provider.dart';
import 'constants/colors.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // TEMP: show exception text in UI during debugging (remove in production)
  ErrorWidget.builder = (FlutterErrorDetails details) {
    return Scaffold(
      appBar: AppBar(title: const Text('Build error')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Text(details.exceptionAsString(), style: const TextStyle(color: Colors.red)),
      ),
    );
  };

  // Initialize Firebase. If you used `flutterfire configure`, use the generated options.
  try {
    // Use DefaultFirebaseOptions if available (generated by flutterfire configure)
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Fallback: initialize with default platform behavior (Android/iOS will read google-services.json/GoogleService-Info.plist)
    await Firebase.initializeApp();
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => MenuProvider()),
        ChangeNotifierProvider(create: (_) => OrderProvider()),
        ChangeNotifierProvider(create: (_) => RiderProvider()),
        // add other providers HomeScreen/AdminDashboard need
      ],
      child: MaterialApp(
        title: "Ouma's Delicacy",
        theme: ThemeData(
          primaryColor: AppColors.primary,
          brightness: Brightness.light,
          scaffoldBackgroundColor: AppColors.background,
          pageTransitionsTheme: PageTransitionsTheme(
            builders: {
              for (final platform in TargetPlatform.values)
                platform: const CupertinoPageTransitionsBuilder(),
            },
          ),
        ),
        darkTheme: ThemeData(
          primaryColor: AppColors.primary,
          brightness: Brightness.dark,
          scaffoldBackgroundColor: const Color(0xff121212),
          cardColor: const Color(0xff1e1e1e),
          // optional : tweak text/button colours if needed
        ),
        themeMode: ThemeMode.system, // follow phone setting
        scrollBehavior: const MaterialScrollBehavior()
            .copyWith(physics: const BouncingScrollPhysics()),
        home: const LoginScreen(),
      ),
    );
  }
}
